# fly.toml app configuration file generated for replicant-frontend on 2025-09-27T16:03:15-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'replicant-frontend'
primary_region = 'sjc'

[build]

[processes]
  app = "node build"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
