# fly.toml app configuration file generated for redditorreplicant on 2025-09-26T17:19:15-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'replicant-backend'
primary_region = 'sjc'

[build]

[processes]
  app = "/app/.venv/bin/uvicorn server:app --host 0.0.0.0 --port 8000 --workers 2"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
