<script lang="ts">
	// No special logic needed for static about page
</script>

<svelte:head>
	<title>About - Reddit or Replicant</title>
</svelte:head>

<div class="min-h-screen text-gray-100" style="background: linear-gradient(180deg, #0a0a0b 0%, #111013 100%)">
	<!-- Fixed Toolbar -->
	<div class="fixed top-0 left-0 right-0 z-50 border-b border-gray-700" style="background: rgba(17, 17, 20, 0.95); backdrop-filter: blur(10px);">
		<div class="max-w-4xl mx-auto px-4 md:px-0 py-3">
			<div class="flex items-center justify-between">
				<a href="/" class="text-lg font-bold cursor-pointer hover:text-blue-300 transition-colors" style="color: #f3f4f6; text-shadow: 0 0 8px rgba(0, 212, 255, 0.1);">
					Reddit or <span class="glitch" data-text="Replicant">Replicant</span>?
				</a>
				<div class="flex items-center gap-4">
					<a href="/selection" class="text-blue-400 hover:text-blue-300 transition-colors text-sm">
						Play Game
					</a>
				</div>
			</div>
		</div>
	</div>

	<!-- Content with top padding to account for fixed toolbar -->
	<div class="pt-16">
		<div class="max-w-4xl mx-auto px-4 md:px-0 py-12">
			<div class="max-w-3xl mx-auto">
				<h1 class="text-4xl font-bold mb-8 text-center" style="color: #f3f4f6; text-shadow: 0 0 12px rgba(0, 212, 255, 0.1);">
					About Reddit or <span class="glitch" data-text="Replicant">Replicant</span>
				</h1>

				<div class="space-y-8 text-gray-200 text-lg leading-relaxed content-text">
					<p>
						In a world where artificial intelligence can generate text indistinguishable from human writing, how can we tell what's real anymore? Your social media feeds, discussion forums, and comment sections may be flooded with AI-generated content designed to manipulate your opinions, emotions, and decisions.
					</p>

					<p>
						<strong class="text-white">Reddit or Replicant</strong> is an interactive experience that challenges you to identify which comments were written by humans and which were generated by AI. Named after the synthetic beings in Blade Runner, "Replicants" represent AI-generated content that mimics human discourse so convincingly that detection becomes nearly impossible.
					</p>

					<p>
						This project exists to raise awareness about a critical issue facing our digital society: the proliferation of AI-generated content in spaces we assume are authentically human. As generative AI technology advances, the line between human and artificial communication continues to blur, making it increasingly difficult to verify the authenticity of online discourse.
					</p>

					<p>
						The implications are profound. When bots and AI systems can participate in conversations, share opinions, and influence discussions at scale, our understanding of public sentiment, consensus, and truth itself becomes compromised. What we perceive as grassroots opinions might be coordinated campaigns. What feels like authentic human expression might be algorithmic manipulation.
					</p>

					<p>
						By experiencing firsthand how challenging it is to distinguish AI from human writing, we hope to foster critical thinking about the content we encounter online. Every comment, every post, every opinion we read should be approached with healthy skepticism about its origins and intentions.
					</p>

					<p class="text-center pt-8">
						<a 
							href="/selection" 
							class="px-8 py-4 text-white text-xl rounded transition-all duration-200 cursor-pointer hover:scale-105 font-semibold inline-block"
							style="background: linear-gradient(135deg, var(--replicant-dark), var(--replicant-light)); border: 1px solid var(--replicant-border); box-shadow: 0 4px 15px var(--replicant-shadow);"
							on:mouseenter={(e) => e.target.style.boxShadow = '0 6px 25px var(--replicant-glow)'}
							on:mouseleave={(e) => e.target.style.boxShadow = '0 4px 15px var(--replicant-shadow)'}
						>
							Test Your Detection Skills
						</a>
					</p>
				</div>
			</div>
		</div>
	</div>
</div>